# Generated by Django 4.2.8 on 2024-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemessage',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
